### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by rgreat** [ase379/gpprofile2017#124]
Project gpprof.exe raised exception class EJumpListItemException with message 'JumpListItem exception: Error -2147024891: Adding a custom category ('Instrument') and its child items to a new jump list'.

Build x86 with Delphi 12.

procedure TfrmMain.ReloadJumpList();

  procedure AddMenu(const aMenu: TGPMRUFiles; const aCategory : string);
  var
    i : integer;
    LCategoryIndex : Integer;
    LPath : string;
  begin
    LCategoryIndex := JumpList1.AddCategory(aCategory);
    for i := 0 to aMenu.PopupMenu.Items.Count-1 do
    begin
      LPath := aMenu.PopupMenu.Items[i].Caption;
      if Length(LPath) < 4 then
        Continue;
      LPath := Copy(LPath,4, 256);
      JumpList1.AddItemToCategory(LCategoryIndex, ChangeFileExt(ExtractFileName(LPath),''),'',AnsiQuotedStr(LPath, '"'));  // <--    Here
    end;
  end;

begin
  JumpList1.ApplicationID := 'GpProf2017';
  JumpList1.CustomCategories.Clear();
  AddMenu(MRU, 'Instrument');
  AddMenu(MRUPrf, 'Analyse');
  // GIS is excluded, as we need to load an instrument project for GIS
end;

**Comment by ase379** [comment]
Please retry with changes
