### ISSUE TITLE
Clicking on `<all units>` checkbox does not produce any result

### ISSUE THREAD

**Issue by Kromster380** [ase379/gpprofile2017#131]
GpProfile v 1.6.0

1. Open new project
2. Move the cursor over the `<all units>` checkbox
3. Observe that the checkbox lights up, indicating that it is interactive
4. Click on it - nothing happens

Same issue with `<all classes>`
However, `<all procedures>` checkbox works as expected - de/selecting all procedures in the list

![image](https://github.com/ase379/gpprofile2017/assets/165903224/88830bc7-cc88-4dfc-8ff2-ff8ee645c54b)

**Comment by ase379** [comment]
Please try https://github.com/ase379/gpprofile2017/releases/download/GpProfile_2017_1.6.0/gpprof_2017_v1.6.0.2.zip
