### ISSUE TITLE
Units tree checkboxes act inconsistently when checking the last element

### ISSUE THREAD

**Issue by Kromster380** [ase379/gpprofile2017#132]
1. Open new project and enable Directory Structure
![image](https://github.com/ase379/gpprofile2017/assets/165903224/71e79157-0a93-4be4-ab54-26567ccedd7f)
2. Expand the tree
3. Click on the last element

Expected result - all tree nodes get checked or unchecked together.

Factual result
After click 1:
![image](https://github.com/ase379/gpprofile2017/assets/165903224/67e83037-af9d-4f5b-88e5-0eb0ca0b2934)

After click 2:
![image](https://github.com/ase379/gpprofile2017/assets/165903224/3d541174-bc62-4f2b-ad91-d4b153bf79ac)

After click 3:
![image](https://github.com/ase379/gpprofile2017/assets/165903224/9b1143e2-f2da-4b3e-b51d-4393c7f5a463)

After click 4:
![image](https://github.com/ase379/gpprofile2017/assets/165903224/948b4330-1733-42fc-a3e5-e5d035201545)

**Comment by ase379** [comment]
Fixed in 1.6.0

**Comment by ase379** [comment]
Please try https://github.com/ase379/gpprofile2017/releases/download/GpProfile_2017_1.6.0/gpprof_2017_v1.6.0.2.zip
