### ISSUE TITLE
`<all procedures>` checkbox acts inconsistently

### ISSUE THREAD

**Issue by Kromster380** [ase379/gpprofile2017#133]
1. Open new project and select a couple of procedures - checkbox is grey (implying being disabled):
![image](https://github.com/ase379/gpprofile2017/assets/165903224/5813dd3d-43a7-4a16-8817-713918b308fd)

 - Why is it disabled? It would be good to still let it work to enable/disable all the procedures in the list

2. Save selection to file, Load it back. Checkbox is blue now (implying being enabled):
![image](https://github.com/ase379/gpprofile2017/assets/165903224/d94bd3a1-4191-4bce-ae44-c97520266cfe)

 - Checkbox works as expected now, allowing to de/select all the procedures in the list.

P.S. Similar issues dwell with <all classes> checkbox (and maybe others).

**Comment by ase379** [comment]
Fixed in 1.6.0
