### ISSUE TITLE
Another checkbox behaviour inconsistency (caused by presence of classless procedures?)

### ISSUE THREAD

**Issue by Kromster380** [ase379/gpprofile2017#134]
1. Open new project with classless procedure:
![image](https://github.com/ase379/gpprofile2017/assets/165903224/ebdf28a1-a090-4c2a-9045-35c77a87355d)

2. Flag `TForm1`. Observe how none of TForm1 procedures got flagged:
![image](https://github.com/ase379/gpprofile2017/assets/165903224/0bf07a55-6b91-4a21-8980-aa2e29f9150e)

3. Instead, select the `<classless procedures>` (without flagging it) - its methods got flagged:
![image](https://github.com/ase379/gpprofile2017/assets/165903224/3c887f63-ec09-42d9-ad62-0c0c6aa25998)

**Comment by ase379** [comment]
Fixed in 1.6.0
