### ISSUE TITLE
Allow to instrument every line in a method

### ISSUE THREAD

**Issue by Kromster380** [ase379/gpprofile2017#142]
Sometimes it could be really handy to be able to just instrument every line in a method. Not every method, just one or two methods.

Especially if there are:
 - RTL or system calls involved which can not be instrumented otherwise
 - procedure is just thousands of lines of code

Of course it will be inefficient and affect measured values, but it could be a great exploratory tool and should not be too much of a stretch to implement.

Something alike:
```delphi
{>>GpProfile} ProfilerEnterProcLine(95,1); try {GpProfile>>}
  a := someLocator.GetSomething;
{>>GpProfile} finally ProfilerExitProcLine(95,1); end; {GpProfile>>}
{>>GpProfile} ProfilerEnterProcLine(95,2); try {GpProfile>>}
  b := a.Foo;
{>>GpProfile} finally ProfilerExitProcLine(95,2); end; {GpProfile>>}
{>>GpProfile} ProfilerEnterProcLine(95,3); try {GpProfile>>}
  c := FizzBuzz(b);
{>>GpProfile} finally ProfilerExitProcLine(95,3); end; {GpProfile>>}
```

**Comment by ase379** [comment]
You can use measure points for that

**Comment by Kromster380** [comment]
Looks like what I need, thank you!
