### ISSUE TITLE
gppMain.dfm missing vstSelectUnits

### ISSUE THREAD

**Issue by kevinv9** [ase379/gpprofile2017#16]
Hi, I download the gpprofile2017/master and found that gppmain.dfm is missing vstSelectUnits: TvirtualstringTree. Looks like the dfm is not in sync with the .pas file.

**Comment by ase379** [comment]
I wanted to switch the selection of the units to the virtual tree list view and left an inconsitent state. 
As the changes I made on the head currently do not work, I reverted them.
I will add the checkable virtual tree list view in an own improvement branch.

Sorry for the inconvinience. 

develop should work again.

**Comment by kevinv9** [comment]
Hi,

 Great job in the converting to VST I have been wanting to do that for long time to get rid of the other components. Thanks
