### ISSUE TITLE
.prf output file

### ISSUE THREAD

**Issue by jplecocq** [ase379/gpprofile2017#94]
Hi everyone

Could you give me some help, about GpProf2017.
I Could recompile source code and create GpProfile 2017  executable.
But when running and debbuging an "instrumented" app, it doesn't generate any *.prf file in order to analyse the project.
I'm missing something?

Best regards

**Comment by ase379** [comment]
Ist next to the output file (e.g. the exe or dll).
You can change this in the project settings...
