### ISSUE TITLE
Cannot find initialization file

### ISSUE THREAD

**Issue by PioPio2** [ase379/gpprofile2017#95]
Hello again,

Sorry, I have followed the instructions, instrumentated the source and build the .exe
When I run the .exe I have the warning "Cannot find initialization file" and the profile cannot be performed.
What am I doing wrong ?

Many thanks
Alberto

**Comment by PioPio2** [comment]
I have found the file in the release folder.

**Comment by ase379** [comment]
Its normally next to the output artefact, you can change this in the project settings...

**Comment by fabvit** [comment]
I am unable to configure where to output the initialization file. It insists saving it in the Release folder even if I am in in Debug build.
@ase379 please can you help to understand where I can change it in the project settings?

**Comment by ase379** [comment]
The configuration of the active configuration of the dproj should be taken. Perhaps you have to set debug as the currenly active setting in delphi.

**Comment by fabvit** [comment]
The currenly active setting in delphi for this project is Debug. All the project artifacts (.exe, .map, .dcu) are currently generated in the Win32/Debug folder. I do not know where to look and what to look for, other than double check that the ctive setting in delphi for this project is Debug.

**Comment by ase379** [comment]
Can you upload the project files ?

**Comment by fabvit** [comment]
Do you mean both .dpr and .dproj?

**Comment by ase379** [comment]
Yes

**Comment by fabvit** [comment]
Attached here the .dproj file (renamed to .txt to allow the upload)
[Locazioni.dproj.txt](https://github.com/ase379/gpprofile2017/files/13263792/Locazioni.dproj.txt)

**Comment by ase379** [comment]
What about the dpr ?

**Comment by fabvit** [comment]
I apologize, here it is the .dpr
[Locazioni.dpr.txt](https://github.com/ase379/gpprofile2017/files/13265352/Locazioni.dpr.txt)

**Comment by ase379** [comment]
I found it, its a bug in the code. I will update the release files.

**Comment by fabvit** [comment]
Thank you so much Andreas! Fantastic! I will monitor Github in the next days for a new binary release.

**Comment by ase379** [comment]
Ist already available, just grab the latest Release.

**Comment by fabvit** [comment]
Andreas thank you for your support: I've downloaded the last build you released yesterday and I can confirm that it works like a charm!
